FROM node:22.4.0-alpine

WORKDIR /app

COPY package.json .
COPY package-lock.json .
RUN npm i

COPY apps apps
COPY libs libs
COPY types types
COPY nx.json .
COPY tsconfig.base.json .
COPY eslint.config.js .
COPY config/custom-environment-variables.json config/custom-environment-variables.json
COPY config/default.json config/default.json

RUN npx nx build mp4-to-gif-api

FROM node:22.4.0-alpine

RUN apk update
RUN apk upgrade
RUN apk add --no-cache ffmpeg

WORKDIR /app

COPY --from=0 /app/dist/apps/mp4-to-gif-api mp4-to-gif-api
COPY --from=0 /app/node_modules node_modules
COPY --from=0 /app/config config

ENTRYPOINT ["node", "/app/mp4-to-gif-api/main.js"]
