version: '3.8'

services:
  minio:
    image: bitnami/minio:2024
    container_name: minio
    network_mode: host
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin-password
    volumes:
      - .mp4-to-gif/minio/data:/data
